### ISSUE TITLE
TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by zeroasterisk** [iriscouch/traceback#7]
```
node_modules/traceback/lib/frame.js:25
  frame.type      = frame.getTypeName()
                          ^
TypeError: Cannot read property 'constructor' of undefined
    at CallSiteGetTypeName (native)
    at Object.make_easy [as make] (/Users/alan/Code/eltoro/portal_v1/webapp/node_modules/traceback/lib/frame.js:25:27)
    at /Users/alan/Code/eltoro/portal_v1/webapp/node_modules/traceback/traceback.js:38:54
```

``` js
    var traceback = require('traceback');
    var stack = traceback();
    var last = stack.pop();
    var tb = '[' + ' in ' + last.file + ' @ ' + last.line + ']';

    for (var i = 1; i <= 3; i++) {
      tb = tb + '/[' + stack[i].name + ' in ' + stack[i].file + ' @ ' + stack[i].line + ']';
    }
```

**Comment by raghuugare** [comment]
I got the same error when I used the `strict` mode. However, it worked in non-strict mode.
