### ISSUE TITLE
TypeError: CallSite method getThis expects CallSite as receiver

### ISSUE THREAD

**Issue by dpnishant** [iriscouch/traceback#9]
I'm facing the following error with the following test code:

### Test Code
```javascript
var traceback = require('traceback');
const crypto = require('crypto');
const fs = require('fs');

fs.readFile(__filename, function () {
  crypto.randomBytes(256, function () {
  	var stack = traceback();
  	console.log(stack[0]); 
  });
});
```
### Error
```javascript
/Users/n/node_modules/traceback/lib/frame.js:24
  frame.this      = frame.getThis()
                          ^

TypeError: CallSite method getThis expects CallSite as receiver
    at CallSite.getThis (<anonymous>)
    at Object.make_easy [as make] (/Users/n/node_modules/traceback/lib/frame.js:24:27)
    at /Users/n/node_modules/traceback/traceback.js:38:54
    at Array.map (<anonymous>)
    at traceback (/Users/n/node_modules/traceback/traceback.js:38:16)
    at Object.<anonymous> (/Users/n/Desktop/trace-test.js:2:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

### Node Version
```sh
➜  Desktop node -v
v8.9.4
```

### traceback Module Version
```sh
➜  Desktop npm list traceback
/Users/n
└── traceback@0.3.1
```

**Comment by ajaysarw** [comment]
I am facing the same issue.
